---
- hosts: all
  serial: 1
  user: root_EB
  become: true
  become_method: sudo
  tasks:
  - name: stopping http
    command: /install/IBM/HTTPServer/bin/apachectl stop
    register: stopped
  - local_action: wait_for host={{ inventory_hostname }} state=stopped delay=3 timeout=4
  - debug: var=stopped.stdout_lines
  - name: starting http
    command: /install/IBM/HTTPServer/bin/apachectl start
    register: started
    when: stopped.changed
  - local_action: wait_for host={{ inventory_hostname }} state=started delay=5 timeout=8
  - debug: var=started.stdout_lines
