---
- hosts: all
  user: root_EB
  become: true
  become_method: sudo
  vars:
     confile: "/install/IBM/HTTPServer/conf/httpd.conf"
     RE1: "^CustomLog\ logs/access_log\ common$"
     L1: "#CustomLog logs/access_log common"
     L2: "CustomLog logs/access_log common env=!log_exclude"
     L3: "SetEnvIf Request_URI '^/navigator/jaxrs/getActions$' log_exclude=true"
  tasks:
   - name: commenting log conf
     lineinfile: 
        path: "{{ confile }}"
        regexp:  "{{ RE1}}"
        line: "{{ L1 }}"
        backup: yes
   - name: inserting new log setting
     lineinfile: 
        path: "{{ confile }}"
        insertafter: "{{ L1  }}"
        line: "{{ L2 }}"
   - name: set exclude uri
     lineinfile: 
        path: "{{ confile }}"
        insertafter: "{{ L2 }}"
        line: "{{ L3 }}"

          
