---
- hosts: all
  user: root_EB
  serial: 1
  become: true
  become_method: sudo
  vars:
      confile: "/etc/sudoers"
      #L1: "^root_EB"
      ######L1: "root ALL=(ALL) ALL"
      #L2: "dimpy   ALL=(ALL)   NOPASSWD: ALL"
      L2: "^dimpy"
  tasks:
   - name: adding new user to sudoers
     lineinfile: 
        path: "{{ confile }}"
        regexp: "{{ L2 }}"
        #line: "{{ L2 }}"
        backup: yes
        state: absent
     #check_mode: yes
     #register: conf
     #failed_when: (conf is changed) or (conf is failed)
