---
- hosts: all
  user: root_EB
  become: True
  become_method: sudo
  gather_facts: false
  vars_prompt:
   - name: pswd
     prompt: "Please Enter App Password?"
     private: no
  roles:
    - site-app-role
