---
- hosts: all
  user: root_EB
  become: yes
  become_method: sudo
  gather_facts: false
  vars_prompt:
   - name: password
     prompt: "Please Enter App Password?"
     private: no
  roles:
    - site_status

